const mongoose = require('mongoose')

const {Schema} = mongoose

const matriculaSchema = new Schema({
   ESTADO: {type: String,require:true},
   N_DNI_ALUMNO: {type: String,require:true},
   TIPO: {type: String, require:true},
   APELLIDO: {type: String, require:true},
   NOMBRE: {type:String,require:true},
   SEXO: {type:String,require:true},
   FECHA_NACIMIENTO: {type:String,require:true},
   LUGAR_NACIMIENTO: {type:String,require:true},
   NACIONALIDAD: {type:String,require:true},
   PROVINCIA_NACIMIENTO: {type:String,require:true},
   EMAIL: {type:String,require:true},
   CUIL:{type:String,require:true},
   NRO_LEGAJO: {type:String,require:true},
   CALLE: {type:String,require:true},
   NRO: {type:String,require:true},
   BARRIO: {type:String,require:true},
   LOCALIDAD: {type:String,require:true},
   PROVINCIA: {type:String,require:true},
   TEL_FIJO:{type:String,require:true},
   TEL_CELULAR: {type:String,require:true},
   NIVEL: {type: String, require:true},
   GRADO: {type: Number,require:true},
   DIVISION: {type: String, require:true},
   DENOMINACION: {type:String,require:true},
   APELLIDO_TUTOR:{type:String,require:true},
   NOMBRE_TUTOR: {type:String,require:true},
   DNI_TUTOR: {type:String,require:true},
   PROFESION_TUTOR: {type:String,require:true},
   RELACION_TUTOR: {type:String,require:true},
   EMAIL_TUTOR: {type:String,require:true},
   EXAMEN_VISUAL: {type:String,require:true},
   CERT_SALUD:{type:String,require:true},
   CERT_BUCO_DENTAL: {type:String,require:true},
   VACUNAS_AL_DIA:{type:String,require:true},
   ANTIVARIOLICA: {type:String,require:true},
   BCG:{type:String,require:true},
   TRIPLE: {type:String,require:true},
   DOBLE: {type:String,require:true},
   SABIN: {type:String,require:true},
   ANTI_SARAMPION: {type:String,require:true}, 
   OTRAS_1: {type:String,require:true},
   OTRAS_2: {type:String,require:true},
   INGRESO: {type:String,require:true},
   EGRESO: {type:String,require:true},
   OBSERVACIONES: {type:Array,require:true},
   REGISTRO: {type:Array,require:true},
},{collection: 'Matricula'});

module.exports = mongoose.model('Matricula', matriculaSchema)
